import { EurekaZoneInfo } from './eureka';
import northHornMap from './northhorn.png';

// https://v2.xivapi.com/api/search?sheets=DynamicEvent&limit=9999&fields=Name@en,Name@de,Name@fr,Name@ja&query=LGBMapRange=0 - Critical Engagements
// https://v2.xivapi.com/api/search?sheets=Fate&limit=9999&fields=Name@en,Name@de,Name@fr,Name@ja&query=EurekaFate=3 - Fates
// https://v2.xivapi.com/api/search?sheets=MKDLore&limit=9999&fields=Name@en,Name@de,Name@fr,Name@ja&query=Unknown5=4 - Occult Records

/* TODO: Write code for alternating cooldowns (e.g., for the "Pots" fates) */

export const zoneInfoNorthHorn: EurekaZoneInfo = {
  mapImage: northHornMap,
  mapWidth: 2048,
  mapHeight: 2048,
  shortName: 'northhorn',
  hasTracker: false,
  onlyShowInactiveWithExplicitRespawns: true,
  treatNMsAsSkirmishes: true,
  mapToPixelXScalar: 50,
  mapToPixelXConstant: -50,
  mapToPixelYScalar: 50,
  mapToPixelYConstant: -50,
  fieldNotes: [
    {
      id: 11,
      name: {
        en: 'Persistent Pots',
        de: 'Der Wunderpott',
        fr: 'Pots persistants',
        ja: 'おねだりポット',
        cn: '撒娇罐',
        ko: '행복한 마법 항아리',
      },
      shortName: {
        en: 'Pots',
        de: 'Wunderpott',
        fr: 'Pots',
        ja: 'ポット',
        cn: '撒娇罐',
        ko: '항아리',
      },
      rarity: 0,
    },
    {
      id: 33,
      name: {
        en: 'Arbatel',
        de: 'Arbatel',
        fr: 'Arbatel',
        ja: 'アルバテル',
        cn: '古术魔典',
        ko: '아르바텔',
      },
      shortName: {
        en: 'Arbatel',
        de: 'Arbatel',
        fr: 'Arbatel',
        ja: 'アルバテル',
        cn: '古术魔典',
        ko: '아르바텔',
      },
      rarity: 0,
    },
    {
      id: 34,
      name: {
        en: 'Tiny Mage',
        de: 'Winzige Magier',
        fr: 'Petit mage',
        ja: 'タイニーメイジ',
        cn: '小小法师',
        ko: '타이니 메이지',
      },
      shortName: {
        en: 'Mage',
        de: 'Magier',
        fr: 'Mage',
        ja: 'メイジ',
        cn: '小小法师',
        ko: '메이지',
      },
      rarity: 0,
    },
    {
      id: 35,
      name: {
        en: 'Algol',
        de: 'Algol',
        fr: 'Algol',
        ja: 'アルゴル',
        cn: '阿尔戈尔',
        ko: '알골',
      },
      shortName: {
        en: 'Algol',
        de: 'Algol',
        fr: 'Algol',
        ja: 'アルゴル',
        cn: '阿尔戈尔',
        ko: '알골',
      },
      rarity: 0,
    },
    {
      id: 38,
      name: {
        en: 'Metamorph',
        de: 'Metamorpha',
        fr: 'Métamorphe',
        ja: 'メタモルファ',
        cn: '变形法师',
        ko: '메타몰퍼',
      },
      shortName: {
        en: 'Metamorph',
        de: 'Metamorpha',
        fr: 'Métamorphe',
        ja: 'メタモルファ',
        cn: '变形法师',
        ko: '메타몰퍼',
      },
      rarity: 0,
    },
    {
      id: 41,
      name: {
        en: 'Pallmagia',
        de: 'Bleicher Magia',
        fr: 'Palimagia',
        ja: 'ペイルマギア',
        cn: '惨白魔人',
        ko: '창백한 마기아',
      },
      shortName: {
        en: 'Pallmagia',
        de: 'Magia',
        fr: 'Palimagia',
        ja: 'マギア',
        cn: '惨白魔人',
        ko: '마기아',
      },
      rarity: 0,
    },
    {
      id: 42,
      name: {
        en: 'Phantom Necromancer',
        de: 'Kreszenter Nekromant',
        fr: 'Nécromancien magi',
        ja: 'マギ・ネクロマンサー',
        cn: '魔亡灵法师',
        ko: '마기 강령술사',
      },
      shortName: {
        en: 'Necromancer',
        de: 'Nekromant',
        fr: 'Nécromancien',
        ja: 'ネクロマンサー',
        cn: '魔亡灵法师',
        ko: '강령술사',
      },
      rarity: 0,
    },
    {
      id: 44,
      name: {
        en: 'The Abductor',
        de: 'Abduktor',
        fr: 'Le Ravisseur',
        ja: 'アブダクター',
        cn: '诱拐魔',
        ko: '유괴자',
      },
      shortName: {
        en: 'Abductor',
        de: 'Abduktor',
        fr: 'Ravisseur',
        ja: 'アブダクター',
        cn: '诱拐魔',
        ko: '유괴자',
      },
      rarity: 0,
    },
    {
      id: 48,
      name: {
        en: 'Claret Dragon',
        de: 'Rubrum-Drache',
        fr: 'Dragon rubrum',
        ja: 'ルブルムドラゴン',
        cn: '赤龙',
        ko: '루브룸 드래곤',
      },
      shortName: {
        en: 'Dragon',
        de: 'Drache',
        fr: 'Dragon',
        ja: 'ドラゴン',
        cn: '赤龙',
        ko: '드래곤',
      },
      rarity: 0,
    },
    {
      id: 50,
      name: {
        en: 'The Alabaster Blade',
        de: 'Alabaster-Klinge',
        fr: 'La Lame d\'albâtre',
        ja: 'アラバスターブレード',
        cn: '雪石膏之剑',
        ko: '설화석고 검사',
      },
      shortName: {
        en: 'Alabaster',
        de: 'Alabaster',
        fr: 'D\'albâtre',
        ja: 'アラバスター',
        cn: '雪石膏之剑',
        ko: '설화석고',
      },
      rarity: 0,
    },
    {
      id: 53,
      name: {
        en: 'Conjured Calofisteri',
        de: 'Calofisteri-Doppelgängerin',
        fr: 'Clone de Calofisteri',
        ja: 'カロフィステリ・ダブル',
        cn: '卡洛菲斯提莉二重身',
        ko: '칼로피스테리 분신',
      },
      shortName: {
        en: 'Calofisteri',
        de: 'Calofisteri',
        fr: 'Calofisteri',
        ja: 'ダブル',
        cn: '卡洛菲斯提莉二重身',
        ko: '칼로피스테리',
      },
      rarity: 0,
    },
  ],
  nms: {
    ragingthrall: {
      label: {
        en: 'Raging Thrall',
        de: 'Mit Kraft und Keule',
        fr: 'Défi : quand le dopage fait des ravages',
        ja: '暴力の牛魔「ミノタウロス・マキア」',
        cn: '暴力牛魔——好战弥诺陶洛斯',
        ko: '폭력적인 소 마물',
      },
      shortLabel: {
        en: 'Thrall',
        de: 'Kraft',
        fr: 'Ravages',
        ja: 'マキア',
        cn: '好战弥诺陶洛斯',
        ko: '마키아',
      },
      x: 35.8,
      y: 25.7,
      fateId: 2074,
    },
    eyetoeye: {
      label: {
        en: 'Eye to Eye',
        de: 'Auge um Auge',
        fr: 'Défi : voyant malveillant',
        ja: '呪いの宝珠「イビルシーア」',
        cn: '诅咒宝珠——邪瞳',
        ko: '저주 거는 보주',
      },
      shortLabel: {
        en: 'Eye',
        de: 'Auge',
        fr: 'Voyant',
        ja: 'イビルシーア',
        cn: '邪瞳',
        ko: '관찰자',
      },
      x: 31.7,
      y: 20.9,
      fateId: 2075,
    },
    shorelineshowdown: {
      label: {
        en: 'Shoreline Showdown',
        de: 'Wassertyrannei',
        fr: 'Défi : chasse gardée',
        ja: '水辺の暴君「レグナントキマイラ」',
        cn: '水边暴君——统领奇美拉',
        ko: '물가의 폭군',
      },
      shortLabel: {
        en: 'Showdown',
        de: 'Tyrannei',
        fr: 'Gardée',
        ja: 'キマイラ',
        cn: '统领奇美拉',
        ko: '키마이라',
      },
      x: 23.3,
      y: 30.8,
      fateId: 2076,
    },
    wavedaway: {
      label: {
        en: 'Waved Away',
        de: 'Mit allen Wassern gewaschen',
        fr: 'Défi : une vie de combats',
        ja: '歴戦水馬「アーチケルピー」',
        cn: '历战水马——凯尔派总领',
        ko: '역전의 수마',
      },
      shortLabel: {
        en: 'Waved',
        de: 'Gewaschen',
        fr: 'Combats',
        ja: 'アーチケルピー',
        cn: '凯尔派总领',
        ko: '켈피',
      },
      x: 28.2,
      y: 16.5,
      fateId: 2077,
    },
    allureoftheoccult: {
      label: {
        en: 'Allure of the Occult',
        de: 'Auf den Atem kommt es an',
        fr: 'Défi : je t\'aime...moi non plus',
        ja: 'ため息モルボル「センシュアル・サンディ」',
        cn: '魔界的叹息——妖艳魔花珊迪',
        ko: '탄식하는 몰볼',
      },
      shortLabel: {
        en: 'Occult',
        de: 'Atem',
        fr: 'T\'aime',
        ja: 'サンディ',
        cn: '妖艳魔花珊迪',
        ko: '샌디',
      },
      x: 13.4,
      y: 16.3,
      fateId: 2078,
    },
    inconstantgardener: {
      label: {
        en: 'Inconstant Gardener',
        de: 'Sing mir das Lied vom Tod',
        fr: 'Défi : la diva destructrice',
        ja: '自滅の歌い手「イアムベー」',
        cn: '自怨自艾的歌手——伊阿姆柏',
        ko: '자멸의 가수',
      },
      shortLabel: {
        en: 'Gardener',
        de: 'Sing',
        fr: 'Diva',
        ja: 'イアムベー」',
        cn: '伊阿姆柏',
        ko: '이암베',
      },
      x: 18,
      y: 11.7,
      fateId: 2079,
    },
    territorialdispute: {
      label: {
        en: 'Territorial Dispute',
        de: 'Der Hund von Kreszentia',
        fr: 'Défi : un froid de loup',
        ja: '遺跡荒らしの氷狼「ルーインハウンド」',
        cn: '狼占狗窝——遗迹冰狼',
        ko: '유적을 어지럽히는 얼음늑대',
      },
      shortLabel: {
        en: 'Dispute',
        de: 'Hund',
        fr: 'Froid ',
        ja: 'ルーインハウンド',
        cn: '遗迹冰狼',
        ko: '사냥개',
      },
      x: 19.6,
      y: 38.7,
      fateId: 2080,
    },
    arottenaffair: {
      label: {
        en: 'A Rotten Affair',
        de: 'Die ewige Wächterin',
        fr: 'Défi : pas de patience pour la pourriture',
        ja: '腐都の守護者「ペイシェント・クリブ」',
        cn: '腐坏街道的守护者——忍耐基路伯',
        ko: '폐허도시 수호자',
      },
      shortLabel: {
        en: 'Affair',
        de: 'Wächterin',
        fr: 'Pourriture',
        ja: 'クリブ',
        cn: '忍耐基路伯',
        ko: '쿠리부',
      },
      x: 12.5,
      y: 5.4,
      fateId: 2081,
    },
    galeforceencounter: {
      label: {
        en: 'Gale-force Encounter',
        de: 'Stürmischer Empfang',
        fr: 'Défi : autant en emporte la tempête',
        ja: '暴風の操者「ストームコーラー」',
        cn: '驾驭自然的巨兽——呼风狮鹫',
        ko: '폭풍 조종자',
      },
      shortLabel: {
        en: 'Encounter',
        de: 'Empfang',
        fr: 'Tempête',
        ja: 'ストームコーラー',
        cn: '呼风狮鹫',
        ko: '폭풍부름이',
      },
      x: 4.2,
      y: 31,
      fateId: 2082,
    },
    scalemodel: {
      label: {
        en: 'Scale Model',
        de: 'Stein zu Stein',
        fr: 'Défi : rideau sur la méduse',
        ja: '模造の蛇人形「デミメデューサ」',
        cn: '仿制的蛇人偶——半灵美杜莎',
        ko: '모조 뱀 인형',
      },
      shortLabel: {
        en: 'Model',
        de: 'Stein',
        fr: 'Méduse',
        ja: 'デミメデューサ',
        cn: '半灵美杜莎',
        ko: '데미메두사',
      },
      x: 8.2,
      y: 20.1,
      fateId: 2083,
    },
    thunderregnum: {
      label: {
        en: 'Thunderregnum',
        de: 'Königliche Arroganz',
        fr: 'Défi : la reine des coeurls brisés',
        ja: '気高き雷獣「クレセントレギナ」',
        cn: '高傲的雷兽——新月女王',
        ko: '고귀한 번개짐승',
      },
      shortLabel: {
        en: 'Thunder',
        de: 'Arroganz',
        fr: 'Coeurls',
        ja: 'クレセントレギナ',
        cn: '新月女王',
        ko: '레기나',
      },
      x: 24.3,
      y: 7.3,
      fateId: 2084,
    },
    inapotofbother: {
      label: {
        en: 'In a Pot of Bother',
        de: 'Wind im Pott',
        fr: 'Se prendre un vent, c\'est pas de pot',
        ja: '飛ばされのマジックポット',
        cn: '被吹飞的魔法罐',
        ko: '날아가는 마법 항아리',
      },
      fieldNotes: 11,
      shortLabel: {
        en: 'Pots',
        de: 'Pott',
        fr: 'Pots',
        ja: 'ポット',
        cn: '魔法罐',
        ko: '항아리',
      },
      x: 11,
      y: 25.8,
      bunny: true,
      fateId: 2073,
      respawnMinutes: 60,
    },
    daylightpottery: {
      label: {
        en: 'Daylight Pottery',
        de: 'Versteckt im Pott',
        fr: 'Cache-cache avec le pot',
        ja: '隠されのマジックポット',
        cn: '被欺负的魔法罐',
        ko: '찾아다니는 마법 항아리',
      },
      fieldNotes: 11,
      shortLabel: {
        en: 'Pots',
        de: 'Pott',
        fr: 'Pot',
        ja: 'ポット',
        cn: '魔法罐',
        ko: '항아리',
      },
      x: 26.2,
      y: 11.6,
      bunny: true,
      fateId: 2072,
      respawnMinutes: 60,
    },
    /* theforkedtowermagic: {
      label: {
        en: 'The Forked Tower: Magic',
        de: 'Der Turm der Magie',
        fr: 'Tour fourchue de la Magie',
        ja: 'フォークタワー：魔の塔',
        cn: '两歧塔 魔之塔',
        ko: '포크 타워: 마의 탑',
      },
      shortLabel: {
        en: 'Tower (Magic)',
        de: 'Turm (Magie)',
        fr: 'Tour (Magie)',
        ja: '塔（魔）',
        cn: '塔（魔）',
        ko: '마의 탑',
      },
      x: 22.7,
      y: 21.6,
      isCritical: true,
      ceKey: 0,
    }, */
    manymouthstofeed: {
      label: {
        en: 'Many Mouths to Feed',
        de: 'Verfressen bis in die Wurzeln',
        fr: 'Défi : appétit vorace',
        ja: '四つ顎の魔樹「ペレキュス」',
        cn: '四颚斧花——提蔛',
        ko: '턱 네 개 마수 \'펠레키스\'',
      },
      shortLabel: {
        en: 'Mouths',
        de: 'Wurzeln',
        fr: 'Appétit',
        ja: 'ペレキュス',
        cn: '提蔛',
        ko: '펠레키스',
      },
      x: 4.1,
      y: 10.3,
      isCritical: true,
      ceKey: 1,
    },
    doubledtrouble: {
      label: {
        en: 'Doubled Trouble',
        de: 'Doppelt gehext hält besser',
        fr: 'Défi : les dérives du clonage',
        ja: '魔女の複製体「カロフィステリ・ダブル」',
        cn: '魔女复制体——卡洛菲斯提莉二重身',
        ko: '마녀의 복제 \'칼로피스테리 분신\'',
      },
      fieldNotes: 53,
      shortLabel: {
        en: 'Trouble',
        de: 'Doppelt',
        fr: 'Clonage',
        ja: 'ダブル',
        cn: '卡洛菲斯提莉二重身',
        ko: '칼로피스테리',
      },
      x: 17.2,
      y: 20.2,
      isCritical: true,
      ceKey: 2,
    },
    quarriedaway: {
      label: {
        en: 'Quarried Away',
        de: 'Schwert und Stein',
        fr: 'Défi : l\'homme à albâtre',
        ja: '白の守護者「アラバスターブレード」',
        cn: '纯白守护者——雪石膏之剑',
        ko: '하얀 수호자 \'설화석고 검사\'',
      },
      fieldNotes: 50,
      shortLabel: {
        en: 'Quarried',
        de: 'Schwert',
        fr: 'Albâtre',
        ja: 'アラバスターブレード',
        cn: '雪石膏之剑',
        ko: '설화석고',
      },
      x: 12,
      y: 8,
      isCritical: true,
      ceKey: 3,
    },
    forbiddenfolios: {
      label: {
        en: 'Forbidden Folios',
        de: 'Verbotenes Wissen',
        fr: 'Défi : magie taboue',
        ja: '禁忌の魔道書「アルバテル」',
        cn: '禁书化形——古术魔典',
        ko: '금단의 마도서 \'아르바텔\'',
      },
      fieldNotes: 33,
      shortLabel: {
        en: 'Folios',
        de: 'Wissen',
        fr: 'Taboue',
        ja: 'アルバテル',
        cn: '古术魔典',
        ko: '아르바텔',
      },
      x: 34.7,
      y: 34.5,
      isCritical: true,
      ceKey: 4,
    },
    cursedresurgence: {
      label: {
        en: 'Cursed Resurgence',
        de: 'Gift und Kralle',
        fr: 'Défi : dragon en décomposition',
        ja: '暗紅の屍竜「ルブルムドラゴン」',
        cn: '暗红尸骸——赤龙',
        ko: '검붉은 시룡 \'루브룸 드래곤\'',
      },
      fieldNotes: 48,
      shortLabel: {
        en: 'Resurgence',
        de: 'Kralle',
        fr: 'Dragon',
        ja: 'ルブルムドラゴン',
        cn: '赤龙',
        ko: '드래곤',
      },
      x: 7.7,
      y: 24.5,
      isCritical: true,
      ceKey: 5,
    },
    imbalanceddiet: {
      label: {
        en: 'Imbalanced Diet',
        de: 'Unersättliches Unheil',
        fr: 'Défi : Algol l\'insatiable',
        ja: '大食の呪鬼「アルゴル」',
        cn: '暴食咒鬼——阿尔戈尔',
        ko: '폭식의 저주괴물 \'알골\'',
      },
      fieldNotes: 35,
      shortLabel: {
        en: 'Diet',
        de: 'Unheil',
        fr: 'Algol',
        ja: 'アルゴル',
        cn: '阿尔戈尔',
        ko: '알골',
      },
      x: 36.7,
      y: 21.4,
      isCritical: true,
      ceKey: 6,
    },
    webofterror: {
      label: {
        en: 'Web of Terror',
        de: 'Wie eine Fliege im Netz',
        fr: 'Défi : cruelles chasseresses',
        ja: '猟奇の母蜘蛛「クレセント・アルケニー」',
        cn: '残暴的母蜘蛛——新月阿剌克涅',
        ko: '엽기적인 어미 거미 \'초승달 아라크네\'',
      },
      shortLabel: {
        en: 'Terror',
        de: 'Fliege',
        fr: 'Cruelles',
        ja: 'アルケニー',
        cn: '新月阿剌克涅',
        ko: '아라크네',
      },
      x: 24.9,
      y: 18.8,
      isCritical: true,
      ceKey: 7,
    },
    abeastunleashed: {
      label: {
        en: 'A Beast Unleashed',
        de: 'Rubinrote Rebellion',
        fr: 'Défi : le familier se rebelle',
        ja: '反逆の使い魔「アトラス・カーバンクル」',
        cn: '叛逆使魔——负隅宝石兽',
        ko: '반역의 사역마 \'아틀라스 카벙클\'',
      },
      shortLabel: {
        en: 'Beast',
        de: 'Rebellion',
        fr: 'Rebelle',
        ja: 'カーバンクル',
        cn: '负隅宝石兽',
        ko: '카벙클',
      },
      x: 26.1,
      y: 28.6,
      isCritical: true,
      ceKey: 8,
    },
    darkartistry: {
      label: {
        en: 'Dark Artistry',
        de: 'Auf Tod komm raus',
        fr: 'Défi : croisade pour un cadavre',
        ja: '死霊使いの亡霊「マギ・ネクロマンサー」',
        cn: '天道好轮回——魔亡灵法师',
        ko: '사령을 다루는 망령 \'마기 강령술사\'',
      },
      fieldNotes: 42,
      shortLabel: {
        en: 'Artistry',
        de: 'Tod',
        fr: 'Cadavre',
        ja: 'ネクロマンサー」',
        cn: '魔亡灵法师',
        ko: '강령술사',
      },
      x: 26,
      y: 4.3,
      isCritical: true,
      ceKey: 9,
    },
    familiartactics: {
      label: {
        en: 'Familiar Tactics',
        de: 'Auf dem Weg der Erleuchtung',
        fr: 'Défi : la voie de l\'orme',
        ja: '求道の人造人間「エルムギガース」',
        cn: '求道的人造人——神木巨人',
        ko: '수행하는 인조 인형 \'엘름 기가스\'',
      },
      shortLabel: {
        en: 'Familiar',
        de: 'Erleuchtung',
        fr: 'L\'orme',
        ja: 'エルムギガース',
        cn: '神木巨人',
        ko: '기가스',
      },
      x: 13.5,
      y: 35.8,
      isCritical: true,
      ceKey: 10,
    },
    appallingbehavior: {
      label: {
        en: 'Appalling Behavior',
        de: 'Verflucht noch eins',
        fr: 'Défi : vert de rancœur',
        ja: '呪いを継ぐ者「ペイルマギア」',
        cn: '诅咒的继承者——惨白魔人',
        ko: '저주를 잇는 자 \'창백한 마기아\'',
      },
      fieldNotes: 41,
      shortLabel: {
        en: 'Behavior',
        de: 'Verflucht',
        fr: 'Vert',
        ja: 'ペイルマギア',
        cn: '惨白魔人',
        ko: '마기아',
      },
      x: 38.2,
      y: 9.8,
      isCritical: true,
      ceKey: 11,
    },
    tinyterror: {
      label: {
        en: 'Tiny Terror',
        de: 'Klein aber oho',
        fr: 'Défi : petits mais costauds',
        ja: '魔道兵団「タイニーメイジ」',
        cn: '魔法军团——小小法师',
        ko: '마도병단 \'타이니 메이지\'',
      },
      fieldNotes: 11,
      shortLabel: {
        en: 'Tiny',
        de: 'Klein',
        fr: 'Petits',
        ja: 'タイニーメイジ',
        cn: '小小法师',
        ko: '메이지',
      },
      x: 24.3,
      y: 35.6,
      isCritical: true,
      ceKey: 12,
    },
    lostonthewind: {
      label: {
        en: 'Lost on the Wind',
        de: 'Vom Winde verweht',
        fr: 'Défi : alerte enlèvement',
        ja: '絶島の誘拐者「アブダクター」',
        cn: '孤岛的绑架犯——诱拐魔',
        ko: '외딴섬의 납치범 \'유괴자\'',
      },
      fieldNotes: 44,
      shortLabel: {
        en: 'Wind',
        de: 'Winde',
        fr: 'Alerte',
        ja: 'アブダクター',
        cn: '诱拐魔',
        ko: '유괴자',
      },
      x: 18.4,
      y: 4.3,
      isCritical: true,
      ceKey: 13,
    },
    aheadofthecompetition: {
      label: {
        en: 'Ahead of the Competition',
        de: 'Mehr Köpfe als Verstand',
        fr: 'Défi : têtes à claques',
        ja: '覚醒の多頭竜「マギ・ヒュドラ」',
        cn: '苏醒的多头龙——魔许德拉',
        ko: '각성한 다두룡 \'마기 히드라\'',
      },
      shortLabel: {
        en: 'Competition',
        de: 'Verstand',
        fr: 'Claques',
        ja: 'ヒュドラ',
        cn: '魔许德拉',
        ko: '히드라',
      },
      x: 19.8,
      y: 31.1,
      isCritical: true,
      ceKey: 14,
    },
    acceptnoimitators: {
      label: {
        en: 'Accept No Imitators',
        de: 'Mieses Mimikry',
        fr: 'Défi : attention aux contrefaçons',
        ja: '変化の使い魔「メタモルファ」',
        cn: '拟态使魔——变形法师',
        ko: '변화하는 사역마 \'메타몰퍼\'',
      },
      fieldNotes: 38,
      shortLabel: {
        en: 'Imitators',
        de: 'Mimikry',
        fr: 'Attention',
        ja: 'メタモルファ',
        cn: '变形法师',
        ko: '메타몰퍼',
      },
      x: 31.4,
      y: 15.2,
      isCritical: true,
      ceKey: 15,
    },
  },
};
