import { EurekaZoneInfo } from './eureka';
import northHornMap from './northhorn.png';

// https://v2.xivapi.com/api/search?sheets=DynamicEvent&limit=9999&fields=Name@en,Name@de,Name@fr,Name@ja&query=LGBMapRange=0 - Critical Engagements
// https://v2.xivapi.com/api/search?sheets=Fate&limit=9999&fields=Name@en,Name@de,Name@fr,Name@ja&query=EurekaFate=3 - Fates
// https://v2.xivapi.com/api/search?sheets=MKDLore&limit=9999&fields=Name@en,Name@de,Name@fr,Name@ja&query=Unknown5=4 - Occult Records

/* TODO: Write code for alternating cooldowns (e.g., for the "Pots" fates) */

export const zoneInfoNorthHorn: EurekaZoneInfo = {
  mapImage: northHornMap,
  mapWidth: 2048,
  mapHeight: 2048,
  shortName: 'northhorn',
  hasTracker: false,
  onlyShowInactiveWithExplicitRespawns: true,
  treatNMsAsSkirmishes: true,
  mapToPixelXScalar: 50,
  mapToPixelXConstant: -50,
  mapToPixelYScalar: 50,
  mapToPixelYConstant: -50,
  fieldNotes: [
    {
      id: 1,
      name: {
        en: 'Persistent Pots',
        de: 'Der Wunderpott',
        fr: 'Pots persistants',
        ja: 'おねだりポット',
      },
      shortName: {
        en: 'Pots',
        de: 'Wunderpott',
        fr: 'Pots',
        ja: 'ポット',
      },
      rarity: 0,
    },
    {
      id: 2,
      name: {
        en: 'Metamorph',
        de: 'Metamorpha',
        fr: 'Métamorphe',
        ja: 'メタモルファ',
      },
      shortName: {
        en: 'Metamorph',
        de: 'Metamorpha',
        fr: 'Métamorphe',
        ja: 'メタモルファ',
      },
      rarity: 0,
    },
    {
      id: 3,
      name: {
        en: 'Bleicher Magia',
        de: 'Pallmagia',
        fr: 'Palimagia',
        ja: 'ペイルマギア',
      },
      shortName: {
        en: 'Magia',
        de: 'Pallmagia',
        fr: 'Palimagia',
        ja: 'マギア',
      },
      rarity: 0,
    },
    {
      id: 4,
      name: {
        en: 'Phantom Necromancer',
        de: 'Kreszenter Nekromant',
        fr: 'Nécromancien magi',
        ja: 'マギ・ネクロマンサー',
      },
      shortName: {
        en: 'Necromancer',
        de: 'Nekromant',
        fr: 'Nécromancien',
        ja: 'ネクロマンサー',
      },
      rarity: 0,
    },
    {
      id: 5,
      name: {
        en: 'The Abductor',
        de: 'Abduktor',
        fr: 'Le Ravisseur',
        ja: 'アブダクター',
      },
      shortName: {
        en: 'Abductor',
        de: 'Abduktor',
        fr: 'Ravisseur',
        ja: 'アブダクター',
      },
      rarity: 0,
    },
    {
      id: 6,
      name: {
        en: 'Claret Dragon',
        de: 'Rubrum-Drache',
        fr: 'Dragon rubrum',
        ja: 'ルブルムドラゴン',
      },
      shortName: {
        en: 'Dragon',
        de: 'Drache',
        fr: 'Dragon',
        ja: 'ドラゴン',
      },
      rarity: 0,
    },
    {
      id: 7,
      name: {
        en: 'The Alabaster Blade',
        de: 'Alabaster-Klinge',
        fr: 'La Lame d\'albâtre',
        ja: 'アラバスターブレード',
      },
      shortName: {
        en: 'Alabaster',
        de: 'Alabaster',
        fr: 'D\'albâtre',
        ja: 'アラバスター',
      },
      rarity: 0,
    },
    {
      id: 8,
      name: {
        en: 'Conjured Calofisteri',
        de: 'Calofisteri-Doppelgängerin',
        fr: 'Clone de Calofisteri',
        ja: 'カロフィステリ・ダブル',
      },
      shortName: {
        en: 'Calofisteri',
        de: 'Calofisteri',
        fr: 'Calofisteri',
        ja: 'ダブル',
      },
      rarity: 0,
    },
    {
      id: 9,
      name: {
        en: 'Arbatel',
        de: 'Arbatel',
        fr: 'Arbatel',
        ja: 'アルバテル',
      },
      shortName: {
        en: 'Arbatel',
        de: 'Arbatel',
        fr: 'Arbatel',
        ja: 'アルバテル',
      },
      rarity: 0,
    },
    {
      id: 10,
      name: {
        en: 'Algol',
        de: 'Algol',
        fr: 'Algol',
        ja: 'アルゴル',
      },
      shortName: {
        en: 'Algol',
        de: 'Algol',
        fr: 'Algol',
        ja: 'アルゴル',
      },
      rarity: 0,
    },
    {
      id: 11,
      name: {
        en: 'Tiny Mage',
        de: 'Winzige Magier',
        fr: 'Petit mage',
        ja: 'タイニーメイジ',
      },
      shortName: {
        en: 'Mage',
        de: 'Magier',
        fr: 'Mage',
        ja: 'メイジ',
      },
      rarity: 0,
    },
  ],
  nms: {
    ragingthrall: {
      label: {
        en: 'Raging Thrall',
        de: 'Mit Kraft und Keule',
        fr: 'Défi : quand le dopage fait des ravages',
        ja: '暴力の牛魔「ミノタウロス・マキア」',
      },
      shortLabel: {
        en: 'Thrall',
        de: 'Kraft',
        fr: 'Ravages',
        ja: 'マキア',
      },
      x: 35.8,
      y: 25.7,
      fateId: 2074,
    },
    eyetoeye: {
      label: {
        en: 'Eye to Eye',
        de: 'Auge um Auge',
        fr: 'Défi : voyant malveillant',
        ja: '呪いの宝珠「イビルシーア」',
      },
      shortLabel: {
        en: 'Eye',
        de: 'Auge',
        fr: 'Voyant',
        ja: 'イビルシーア',
      },
      x: 31.7,
      y: 20.9,
      fateId: 2075,
    },
    shorelineshowdown: {
      label: {
        en: 'Shoreline Showdown',
        de: 'Wassertyrannei',
        fr: 'Défi : chasse gardée',
        ja: '水辺の暴君「レグナントキマイラ」',
      },
      shortLabel: {
        en: 'Showdown',
        de: 'Tyrannei',
        fr: 'Gardée',
        ja: 'キマイラ',
      },
      x: 23.3,
      y: 30.8,
      fateId: 2076,
    },
    wavedaway: {
      label: {
        en: 'Waved Away',
        de: 'Mit allen Wassern gewaschen',
        fr: 'Défi : une vie de combats',
        ja: '歴戦水馬「アーチケルピー」',
      },
      shortLabel: {
        en: 'Waved',
        de: 'Gewaschen',
        fr: 'Combats',
        ja: 'アーチケルピー',
      },
      x: 28.2,
      y: 16.5,
      fateId: 2077,
    },
    allureoftheoccult: {
      label: {
        en: 'Allure of the Occult',
        de: 'Auf den Atem kommt es an',
        fr: 'Défi : je t\'aime...moi non plus',
        ja: 'ため息モルボル「センシュアル・サンディ」',
      },
      shortLabel: {
        en: 'Occult',
        de: 'Atem',
        fr: 'T\'aime',
        ja: 'サンディ',
      },
      x: 13.4,
      y: 16.3,
      fateId: 2078,
    },
    inconstantgardener: {
      label: {
        en: 'Inconstant Gardener',
        de: 'Sing mir das Lied vom Tod',
        fr: 'Défi : la diva destructrice',
        ja: '自滅の歌い手「イアムベー」',
      },
      shortLabel: {
        en: 'Gardener',
        de: 'Sing',
        fr: 'Diva',
        ja: 'イアムベー」',
      },
      x: 18,
      y: 11.7,
      fateId: 2079,
    },
    territorialdispute: {
      label: {
        en: 'Territorial Dispute',
        de: 'Der Hund von Kreszentia',
        fr: 'Défi : un froid de loup',
        ja: '遺跡荒らしの氷狼「ルーインハウンド」',
      },
      shortLabel: {
        en: 'Dispute',
        de: 'Hund',
        fr: 'Froid ',
        ja: 'ルーインハウンド',
      },
      x: 19.6,
      y: 38.7,
      fateId: 2080,
    },
    arottenaffair: {
      label: {
        en: 'A Rotten Affair',
        de: 'Die ewige Wächterin',
        fr: 'Défi : pas de patience pour la pourriture',
        ja: '腐都の守護者「ペイシェント・クリブ」',
      },
      shortLabel: {
        en: 'Affair',
        de: 'Wächterin',
        fr: 'Pourriture',
        ja: 'クリブ',
      },
      x: 12.5,
      y: 5.4,
      fateId: 2081,
    },
    galeforceencounter: {
      label: {
        en: 'Gale-force Encounter',
        de: 'Stürmischer Empfang',
        fr: 'Défi : autant en emporte la tempête',
        ja: '暴風の操者「ストームコーラー」',
      },
      shortLabel: {
        en: 'Encounter',
        de: 'Empfang',
        fr: 'Tempête',
        ja: 'ストームコーラー',
      },
      x: 4.2,
      y: 31,
      fateId: 2082,
    },
    scalemodel: {
      label: {
        en: 'Scale Model',
        de: 'Stein zu Stein',
        fr: 'Défi : rideau sur la méduse',
        ja: '模造の蛇人形「デミメデューサ」',
      },
      shortLabel: {
        en: 'Model',
        de: 'Stein',
        fr: 'Méduse',
        ja: 'デミメデューサ',
      },
      x: 8.2,
      y: 20.1,
      fateId: 2083,
    },
    thunderregnum: {
      label: {
        en: 'Thunderregnum',
        de: 'Königliche Arroganz',
        fr: 'Défi : la reine des coeurls brisés',
        ja: '気高き雷獣「クレセントレギナ」',
      },
      shortLabel: {
        en: 'Thunder',
        de: 'Arroganz',
        fr: 'Coeurls',
        ja: 'クレセントレギナ',
      },
      x: 24.3,
      y: 7.3,
      fateId: 2084,
    },
    inapotofbother: {
      label: {
        en: 'In a Pot of Bother',
        de: 'Wind im Pott',
        fr: 'Se prendre un vent, c\'est pas de pot',
        ja: '飛ばされのマジックポット',
      },
      fieldNotes: 1,
      shortLabel: {
        en: 'Pots',
        de: 'Pott',
        fr: 'Pots',
        ja: 'ポット',
      },
      x: 11,
      y: 25.8,
      bunny: true,
      fateId: 2073,
      respawnMinutes: 60,
    },
    daylightpottery: {
      label: {
        en: 'Daylight Pottery',
        de: 'Versteckt im Pott',
        fr: 'Cache-cache avec le pot',
        ja: '隠されのマジックポット',
      },
      fieldNotes: 1,
      shortLabel: {
        en: 'Pots',
        de: 'Pott',
        fr: 'Pot',
        ja: 'ポット',
      },
      x: 26.2,
      y: 11.6,
      bunny: true,
      fateId: 2072,
      respawnMinutes: 60,
    },
    /* theforkedtowermagic: {
      label: {
        en: 'The Forked Tower: Magic',
        de: 'Der Turm der Magie',
        fr: 'Tour fourchue de la Magie',
        ja: 'フォークタワー：魔の塔',
      },
      shortLabel: {
        en: 'Tower (Magic)',
        de: 'Turm (Magie)',
        fr: 'Tour (Magie)',
        ja: '塔（魔）',
      },
      x: 22.7,
      y: 21.6,
      isCritical: true,
      ceKey: 0,
    }, */
    manymouthstofeed: {
      label: {
        en: 'Many Mouths to Feed',
        de: 'Verfressen bis in die Wurzeln',
        fr: 'Défi : appétit vorace',
        ja: '四つ顎の魔樹「ペレキュス」',
      },
      shortLabel: {
        en: 'Mouths',
        de: 'Wurzeln',
        fr: 'Appétit',
        ja: 'ペレキュス',
      },
      x: 4.1,
      y: 10.3,
      isCritical: true,
      ceKey: 1,
    },
    doubledtrouble: {
      label: {
        en: 'Doubled Trouble',
        de: 'Doppelt gehext hält besser',
        fr: 'Défi : les dérives du clonage',
        ja: '魔女の複製体「カロフィステリ・ダブル」',
      },
      fieldNotes: 8,
      shortLabel: {
        en: 'Trouble',
        de: 'Doppelt',
        fr: 'Clonage',
        ja: 'ダブル',
      },
      x: 17.2,
      y: 20.2,
      isCritical: true,
      ceKey: 2,
    },
    quarriedaway: {
      label: {
        en: 'Quarried Away',
        de: 'Schwert und Stein',
        fr: 'Défi : l\'homme à albâtre',
        ja: '白の守護者「アラバスターブレード」',
      },
      fieldNotes: 7,
      shortLabel: {
        en: 'Quarried',
        de: 'Schwert',
        fr: 'Albâtre',
        ja: 'アラバスターブレード',
      },
      x: 12,
      y: 8,
      isCritical: true,
      ceKey: 3,
    },
    forbiddenfolios: {
      label: {
        en: 'Forbidden Folios',
        de: 'Verbotenes Wissen',
        fr: 'Défi : magie taboue',
        ja: '禁忌の魔道書「アルバテル」',
      },
      fieldNotes: 9,
      shortLabel: {
        en: 'Folios',
        de: 'Wissen',
        fr: 'Taboue',
        ja: 'アルバテル',
      },
      x: 34.7,
      y: 34.5,
      isCritical: true,
      ceKey: 4,
    },
    cursedresurgence: {
      label: {
        en: 'Cursed Resurgence',
        de: 'Gift und Kralle',
        fr: 'Défi : dragon en décomposition',
        ja: '暗紅の屍竜「ルブルムドラゴン」',
      },
      fieldNotes: 6,
      shortLabel: {
        en: 'Resurgence',
        de: 'Kralle',
        fr: 'Dragon',
        ja: 'ルブルムドラゴン',
      },
      x: 7.7,
      y: 24.5,
      isCritical: true,
      ceKey: 5,
    },
    imbalanceddiet: {
      label: {
        en: 'Imbalanced Diet',
        de: 'Unersättliches Unheil',
        fr: 'Défi : Algol l\'insatiable',
        ja: '大食の呪鬼「アルゴル」',
      },
      fieldNotes: 10,
      shortLabel: {
        en: 'Diet',
        de: 'Unheil',
        fr: 'Algol',
        ja: 'アルゴル',
      },
      x: 36.7,
      y: 21.4,
      isCritical: true,
      ceKey: 6,
    },
    webofterror: {
      label: {
        en: 'Web of Terror',
        de: 'Wie eine Fliege im Netz',
        fr: 'Défi : cruelles chasseresses',
        ja: '猟奇の母蜘蛛「クレセント・アルケニー」',
      },
      shortLabel: {
        en: 'Terror',
        de: 'Fliege',
        fr: 'Cruelles',
        ja: 'アルケニー',
      },
      x: 24.9,
      y: 18.8,
      isCritical: true,
      ceKey: 7,
    },
    abeastunleashed: {
      label: {
        en: 'A Beast Unleashed',
        de: 'Rubinrote Rebellion',
        fr: 'Défi : le familier se rebelle',
        ja: '反逆の使い魔「アトラス・カーバンクル」',
      },
      shortLabel: {
        en: 'Beast',
        de: 'Rebellion',
        fr: 'Rebelle',
        ja: 'カーバンクル',
      },
      x: 26.1,
      y: 28.6,
      isCritical: true,
      ceKey: 8,
    },
    darkartistry: {
      label: {
        en: 'Dark Artistry',
        de: 'Auf Tod komm raus',
        fr: 'Défi : croisade pour un cadavre',
        ja: '死霊使いの亡霊「マギ・ネクロマンサー」',
      },
      fieldNotes: 4,
      shortLabel: {
        en: 'Artistry',
        de: 'Tod',
        fr: 'Cadavre',
        ja: 'ネクロマンサー」',
      },
      x: 26,
      y: 4.3,
      isCritical: true,
      ceKey: 9,
    },
    familiartactics: {
      label: {
        en: 'Familiar Tactics',
        de: 'Auf dem Weg der Erleuchtung',
        fr: 'Défi : la voie de l\'orme',
        ja: '求道の人造人間「エルムギガース」',
      },
      shortLabel: {
        en: 'Familiar',
        de: 'Erleuchtung',
        fr: 'L\'orme',
        ja: 'エルムギガース',
      },
      x: 13.5,
      y: 35.8,
      isCritical: true,
      ceKey: 10,
    },
    appallingbehavior: {
      label: {
        en: 'Appalling Behavior',
        de: 'Verflucht noch eins',
        fr: 'Défi : vert de rancœur',
        ja: '呪いを継ぐ者「ペイルマギア」',
      },
      fieldNotes: 3,
      shortLabel: {
        en: 'Behavior',
        de: 'Verflucht',
        fr: 'Vert',
        ja: 'ペイルマギア',
      },
      x: 38.2,
      y: 9.8,
      isCritical: true,
      ceKey: 11,
    },
    tinyterror: {
      label: {
        en: 'Tiny Terror',
        de: 'Klein aber oho',
        fr: 'Défi : petits mais costauds',
        ja: '魔道兵団「タイニーメイジ」',
      },
      fieldNotes: 11,
      shortLabel: {
        en: 'Tiny',
        de: 'Klein',
        fr: 'Petits',
        ja: 'タイニーメイジ',
      },
      x: 24.3,
      y: 35.6,
      isCritical: true,
      ceKey: 12,
    },
    lostonthewind: {
      label: {
        en: 'Lost on the Wind',
        de: 'Vom Winde verweht',
        fr: 'Défi : alerte enlèvement',
        ja: '絶島の誘拐者「アブダクター」',
      },
      fieldNotes: 5,
      shortLabel: {
        en: 'Wind',
        de: 'Winde',
        fr: 'Alerte',
        ja: 'アブダクター',
      },
      x: 18.4,
      y: 4.3,
      isCritical: true,
      ceKey: 13,
    },
    aheadofthecompetition: {
      label: {
        en: 'Ahead of the Competition',
        de: 'Mehr Köpfe als Verstand',
        fr: 'Défi : têtes à claques',
        ja: '覚醒の多頭竜「マギ・ヒュドラ」',
      },
      shortLabel: {
        en: 'Competition',
        de: 'Verstand',
        fr: 'Claques',
        ja: 'ヒュドラ',
      },
      x: 19.8,
      y: 31.1,
      isCritical: true,
      ceKey: 14,
    },
    acceptnoimitators: {
      label: {
        en: 'Accept No Imitators',
        de: 'Mieses Mimikry',
        fr: 'Défi : attention aux contrefaçons',
        ja: '変化の使い魔「メタモルファ」',
      },
      fieldNotes: 2,
      shortLabel: {
        en: 'Imitators',
        de: 'Mimikry',
        fr: 'Attention',
        ja: 'メタモルファ',
      },
      x: 31.4,
      y: 15.2,
      isCritical: true,
      ceKey: 15,
    },
  },
};
