// Auto-generated from gen_ce_info_and_maps.ts
// DO NOT EDIT THIS FILE DIRECTLY

import { CeInfoType } from '../types/ce';

const data: CeInfoType = {
  'ABeastUnleashed': {
    'directorId': '3C0',
    'name': {
      'cn': '叛逆使魔——负隅宝石兽',
      'de': 'Rubinrote Rebellion',
      'en': 'A Beast Unleashed',
      'fr': 'Défi : le familier se rebelle',
      'ja': '反逆の使い魔「アトラス・カーバンクル」',
      'ko': '반역의 사역마 \'아틀라스 카벙클\'',
    },
  },
  'AcceptNoImitators': {
    'directorId': '3CB',
    'name': {
      'cn': '拟态使魔——变形法师',
      'de': 'Mieses Mimikry',
      'en': 'Accept No Imitators',
      'fr': 'Défi : attention aux contrefaçons',
      'ja': '変化の使い魔「メタモルファ」',
      'ko': '변화하는 사역마 \'메타몰퍼\'',
    },
  },
  'AheadOfTheCompetition': {
    'directorId': '3BC',
    'name': {
      'cn': '苏醒的多头龙——魔许德拉',
      'de': 'Mehr Köpfe als Verstand',
      'en': 'Ahead of the Competition',
      'fr': 'Défi : têtes à claques',
      'ja': '覚醒の多頭竜「マギ・ヒュドラ」',
      'ko': '각성한 다두룡 \'마기 히드라\'',
    },
  },
  'AppallingBehavior': {
    'directorId': '3BA',
    'name': {
      'cn': '诅咒的继承者——惨白魔人',
      'de': 'Verflucht noch eins',
      'en': 'Appalling Behavior',
      'fr': 'Défi : vert de rancœur',
      'ja': '呪いを継ぐ者「ペイルマギア」',
      'ko': '저주를 잇는 자 \'창백한 마기아\'',
    },
  },
  'CursedResurgence': {
    'directorId': '3B9',
    'name': {
      'cn': '暗红尸骸——赤龙',
      'de': 'Gift und Kralle',
      'en': 'Cursed Resurgence',
      'fr': 'Défi : dragon en décomposition',
      'ja': '暗紅の屍竜「ルブルムドラゴン」',
      'ko': '검붉은 시룡 \'루브룸 드래곤\'',
    },
  },
  'DarkArtistry': {
    'directorId': '3A8',
    'name': {
      'cn': '天道好轮回——魔亡灵法师',
      'de': 'Auf Tod komm raus',
      'en': 'Dark Artistry',
      'fr': 'Défi : croisade pour un cadavre',
      'ja': '死霊使いの亡霊「マギ・ネクロマンサー」',
      'ko': '사령을 다루는 망령 \'마기 강령술사\'',
    },
  },
  'DoubledTrouble': {
    'directorId': '398',
    'name': {
      'cn': '魔女复制体——卡洛菲斯提莉二重身',
      'de': 'Doppelt gehext hält besser',
      'en': 'Doubled Trouble',
      'fr': 'Défi : les dérives du clonage',
      'ja': '魔女の複製体「カロフィステリ・ダブル」',
      'ko': '마녀의 복제 \'칼로피스테리 분신\'',
    },
  },
  'FamiliarTactics': {
    'directorId': '390',
    'name': {
      'cn': '求道的人造人——神木巨人',
      'de': 'Auf dem Weg der Erleuchtung',
      'en': 'Familiar Tactics',
      'fr': 'Défi : la voie de l\'orme',
      'ja': '求道の人造人間「エルムギガース」',
      'ko': '수행하는 인조 인형 \'엘름 기가스\'',
    },
  },
  'ForbiddenFolios': {
    'directorId': '39A',
    'name': {
      'cn': '禁书化形——古术魔典',
      'de': 'Verbotenes Wissen',
      'en': 'Forbidden Folios',
      'fr': 'Défi : magie taboue',
      'ja': '禁忌の魔道書「アルバテル」',
      'ko': '금단의 마도서 \'아르바텔\'',
    },
  },
  'ImbalancedDiet': {
    'directorId': '3BF',
    'name': {
      'cn': '暴食咒鬼——阿尔戈尔',
      'de': 'Unersättliches Unheil',
      'en': 'Imbalanced Diet',
      'fr': 'Défi : Algol l\'insatiable',
      'ja': '大食の呪鬼「アルゴル」',
      'ko': '폭식의 저주괴물 \'알골\'',
    },
  },
  'LostOnTheWind': {
    'directorId': '3A9',
    'name': {
      'cn': '孤岛的绑架犯——诱拐魔',
      'de': 'Vom Winde verweht',
      'en': 'Lost on the Wind',
      'fr': 'Défi : alerte enlèvement',
      'ja': '絶島の誘拐者「アブダクター」',
      'ko': '외딴섬의 납치범 \'유괴자\'',
    },
  },
  'ManyMouthsToFeed': {
    'directorId': '39B',
    'name': {
      'cn': '四颚斧花——提蔛',
      'de': 'Verfressen bis in die Wurzeln',
      'en': 'Many Mouths to Feed',
      'fr': 'Défi : appétit vorace',
      'ja': '四つ顎の魔樹「ペレキュス」',
      'ko': '턱 네 개 마수 \'펠레키스\'',
    },
  },
  'QuarriedAway': {
    'directorId': '397',
    'name': {
      'cn': '纯白守护者——雪石膏之剑',
      'de': 'Schwert und Stein',
      'en': 'Quarried Away',
      'fr': 'Défi : l\'homme à albâtre',
      'ja': '白の守護者「アラバスターブレード」',
      'ko': '하얀 수호자 \'설화석고 검사\'',
    },
  },
  'TheForkedTowerMagic': {
    'directorId': '389',
    'name': {
      'cn': '两岐塔 魔之塔',
      'de': 'Der Turm der Magie',
      'en': 'The Forked Tower: Magic',
      'fr': 'Tour fourchue de la Magie',
      'ja': 'フォークタワー：魔の塔',
      'ko': '포크 타워: 마의 탑',
    },
  },
  'TinyTerror': {
    'directorId': '3CC',
    'name': {
      'cn': '魔法军团——小小法师',
      'de': 'Klein aber oho',
      'en': 'Tiny Terror',
      'fr': 'Défi : petits mais costauds',
      'ja': '魔道兵団「タイニーメイジ」',
      'ko': '마도병단 \'타이니 메이지\'',
    },
  },
  'WebOfTerror': {
    'directorId': '3CA',
    'name': {
      'cn': '残暴的母蜘蛛——新月阿剌克涅',
      'de': 'Wie eine Fliege im Netz',
      'en': 'Web of Terror',
      'fr': 'Défi : cruelles chasseresses',
      'ja': '猟奇の母蜘蛛「クレセント・アルケニー」',
      'ko': '엽기적인 어미 거미 \'초승달 아라크네\'',
    },
  },
} as const;

export default data;
