// Auto-generated from gen_ce_info_and_maps.ts
// DO NOT EDIT THIS FILE DIRECTLY

import { CEMap } from '../types/ce';

import NorthHornCEs from './north_horn_encounters';

const data: CEMap<typeof NorthHornCEs> = {
  '389': 'TheForkedTowerMagic',
  '390': 'FamiliarTactics',
  '397': 'QuarriedAway',
  '398': 'DoubledTrouble',
  '39A': 'ForbiddenFolios',
  '39B': 'ManyMouthsToFeed',
  '3A8': 'DarkArtistry',
  '3A9': 'LostOnTheWind',
  '3B9': 'CursedResurgence',
  '3BA': 'AppallingBehavior',
  '3BC': 'AheadOfTheCompetition',
  '3BF': 'ImbalancedDiet',
  '3C0': 'ABeastUnleashed',
  '3CA': 'WebOfTerror',
  '3CB': 'AcceptNoImitators',
  '3CC': 'TinyTerror',
} as const;

export default data;
