name: 'Setup Node and run npm ci'
description: "run actions/setup-node and `npm ci`"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        # 24.17 has a bug that breaks our workflows
        # 26 introduces changes that break our workflows
        # @TODO: remove upper restriction once dependencies no longer fail on 26
        node-version: '>=24.18.0 <25'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install Dependencies
      shell: bash
      run: npm ci
